FROM golang:alpine AS builder
ADD ./metallb /metallb
WORKDIR /metallb/speaker
RUN go build .

FROM busybox:1.34.0
COPY --from=builder /metallb/speaker/speaker /bin/metallb-speaker
USER nobody
ENTRYPOINT [ "/bin/metallb-speaker" ]
