FROM golang:alpine AS builder
ADD ./metallb /metallb
WORKDIR /metallb/speaker
RUN go build .

FROM alpine:3.15.0
COPY --from=builder /metallb/speaker/speaker /bin/metallb-speaker
USER nobody
ENTRYPOINT [ "/bin/metallb-speaker" ]
