FROM golang:alpine AS builder
ADD ./metallb /metallb
WORKDIR /metallb/controller
RUN go build .

FROM alpine:3.14.3
COPY --from=builder /metallb/controller/controller /bin/metallb-controller
USER nobody
ENTRYPOINT [ "/bin/metallb-controller" ]
